<#
.SYNOPSIS
    Shared documentation-pipeline functions for the xFACts platform.

.DESCRIPTION
    Functions common to the documentation-pipeline scripts (Publish-GitHubRepository
    and the pipeline wrapper): extraction of user SQL object definitions from the
    catalog, generation of the Platform Registry markdown snapshot from the registry
    tables, the GitHub REST layer (headers, repository tree retrieval, single-file
    create/update/delete, and local git blob SHA computation), the Object_Registry
    enrichment lookup, and the shared manifest builder that rebuilds the segmented
    manifest set from the live GitHub repository tree and pushes the changed
    manifests. Dot-source this file after xFACts-OrchestratorFunctions.ps1 and after
    Initialize-XFActsScript, since the functions here call Get-SqlData and Write-Log
    from that shared file.

.COMPONENT
    Documentation.Pipeline

.NOTES
    File Name : xFACts-DocPipelineFunctions.ps1
    Location  : E:\xFACts-PowerShell\xFACts-DocPipelineFunctions.ps1

    FILE ORGANIZATION
    -----------------
    CHANGELOG: CHANGE HISTORY
    CONSTANTS: REGISTRY EXPORT DEFINITIONS
    CONSTANTS: MANIFEST SEGMENTS
    FUNCTIONS: SQL OBJECT EXTRACTION
    FUNCTIONS: REGISTRY EXPORT
    FUNCTIONS: GITHUB REST API
    FUNCTIONS: OBJECT REGISTRY LOOKUP
    FUNCTIONS: MANIFEST GENERATION
#>

<# ============================================================================
   CHANGELOG: CHANGE HISTORY
   ----------------------------------------------------------------------------
   Dated change history for this file, most recent first. Authoritative version
   tracking lives in dbo.System_Metadata (component Documentation.Pipeline);
   this section records what changed and when.
   Prefix: (none)
   ============================================================================ #>

# 2026-07-21  Pipeline flip (Task 1). Absorbed the GitHub REST layer from
#             Publish-GitHubRepository.ps1 (Get-GitHubHeaders, Get-RepoTree,
#             Push-GitHubFile, Remove-GitHubFile, Get-GitBlobSha) so both the
#             publisher and the new shared manifest builder sit on one GitHub API
#             layer with no duplication. Added the $script:ManifestSegments
#             routing table, Get-ObjectRegistryLookup and Resolve-ObjectRegistryEntry
#             (the Object_Registry enrichment lifted out of the publisher audit),
#             and Publish-RepositoryManifests: the single manifest builder. It
#             reads the live GitHub repository tree at build time (so the manifest
#             is correct by construction regardless of caller or staging state),
#             classifies each path authored or generated by prefix, enriches from
#             Object_Registry, and pushes only the changed segment and master
#             manifests. Called by the publisher (unless suppressed) and by the
#             pipeline's dedicated manifest step.
# 2026-07-21  Get-SqlObjectDefinitions now excludes retired platform schemas at
#             extraction via a named $ExcludedSchemas list (currently Legacy),
#             applied alongside the sys/INFORMATION_SCHEMA catalog exclusions.
#             Legacy objects are treated as nonexistent - they never reach the
#             repository or the publish audit. Add a schema name to the list to
#             drop it from every extraction in one edit.
# 2026-06-20  Get-RegistryExportMarkdown now returns a hashtable with Markdown
#             and TableCount instead of a bare markdown string, so callers can
#             report how many registry tables the snapshot covered.
# 2026-06-20  Initial implementation. Lifted Get-SqlObjectDefinitions (user SQL
#             object definition extraction) and Get-RegistryExportMarkdown
#             (Platform Registry markdown generation) out of per-script copies
#             in Consolidate-UploadFiles and Publish-GitHubRepository into one
#             shared scoped helper. The $RegistryExports table set moved here as
#             the single source of which registry tables the snapshot includes.

<# ============================================================================
   CONSTANTS: REGISTRY EXPORT DEFINITIONS
   ----------------------------------------------------------------------------
   The registry tables included in the Platform Registry markdown snapshot. Each
   entry is a Title and the Query whose result set renders as one markdown table
   in the generated document. This list is the single source of which registry
   tables the snapshot covers.
   Prefix: (none)
   ============================================================================ #>

# Registry tables exported to the Platform Registry markdown snapshot, in order.
$script:RegistryExports = @(
    @{
        Title = "Module Registry"
        Query = "SELECT module_name, description FROM dbo.Module_Registry WHERE is_active = 1 ORDER BY module_name"
    },
    @{
        Title = "Component Registry"
        Query = "SELECT module_name, component_name, description, cc_prefix, doc_page_id, doc_title, doc_json_schema, doc_json_categories, doc_cc_slug, doc_sort_order, doc_section_order FROM dbo.Component_Registry WHERE is_active = 1 ORDER BY module_name, component_name"
    },
    @{
        Title = "Object Registry"
        Query = "SELECT component_name, object_name, object_category, object_type, object_path, description FROM dbo.Object_Registry WHERE is_active = 1 ORDER BY component_name, object_category, object_type, object_name"
    },
    @{
        Title = "Nav Registry"
        Query = "SELECT page_route, nav_label, display_title, description, section_key, sort_order, doc_page_id, show_in_nav, show_on_home FROM dbo.RBAC_NavRegistry WHERE is_active = 1 ORDER BY section_key, sort_order, page_route"
    },
    @{
        Title = "Process Registry"
        Query = "SELECT module_name, process_name, description, script_path, procedure_name, execution_mode, dependency_group, interval_seconds, scheduled_time, timeout_seconds, run_mode, allow_concurrent, cc_engine_slug, cc_engine_label, cc_page_route, cc_sort_order FROM Orchestrator.ProcessRegistry ORDER BY dependency_group, module_name, process_name"
    },
    @{
        Title = "Global Configuration"
        Query = "SELECT module_name, category, setting_name, setting_value, data_type, description FROM dbo.GlobalConfig WHERE is_active = 1 ORDER BY module_name, category, setting_name"
    }
)

<# ============================================================================
   CONSTANTS: MANIFEST SEGMENTS
   ----------------------------------------------------------------------------
   The segment manifest routing table, most-specific prefix first. Each collected
   repository path is routed to the first entry whose Prefix it starts with; the
   same table drives sub-manifest generation and is emitted in the master manifest
   so the owning segment of any path is resolvable from the master alone. This is
   the single source of the manifest segmentation, shared by every caller of
   Publish-RepositoryManifests.
   Prefix: (none)
   ============================================================================ #>

# Segment manifest routing table (most-specific prefix first).
$script:ManifestSegments = @(
    @{ Key = "cc-docs";       Prefix = "xFACts-ControlCenter/public/docs/"; Filename = "manifest-cc-docs.json";       Title = "Control Center Documentation Site" }
    @{ Key = "cc-app";        Prefix = "xFACts-ControlCenter/";             Filename = "manifest-cc-app.json";        Title = "Control Center Application" }
    @{ Key = "powershell";    Prefix = "xFACts-PowerShell/";                Filename = "manifest-powershell.json";    Title = "PowerShell Scripts" }
    @{ Key = "documentation"; Prefix = "xFACts-Documentation/";             Filename = "manifest-documentation.json"; Title = "Documentation and Working Files" }
    @{ Key = "generated";     Prefix = "xFACts-Generated/";                 Filename = "manifest-generated.json";     Title = "Generated Artifacts (SQL, DDL, Markdown, Registry)" }
)

<# ============================================================================
   FUNCTIONS: SQL OBJECT EXTRACTION
   ----------------------------------------------------------------------------
   Extraction of user-defined SQL object definitions (procedures, triggers,
   functions, views) from the catalog. Returns the raw definition rows so each
   caller can render or persist them however it needs.
   Prefix: (none)
   ============================================================================ #>

# Returns the T-SQL definition of every user SQL module (procs, triggers, functions, views) as raw rows.
function Get-SqlObjectDefinitions {
    param(
        [string]$Instance = $script:XFActsServerInstance,
        [string]$DatabaseName = $script:XFActsDatabase
    )

    # Platform schemas treated as nonexistent by the pipeline. Legacy is retired
    # content excluded here at extraction so it never reaches the repository or
    # the publish audit. Add a schema name to drop it from every extraction.
    $ExcludedSchemas = @('Legacy')
    # Render the exclusion list as a quoted, comma-separated SQL set literal.
    $excludedSchemaList = ($ExcludedSchemas | ForEach-Object { "'$_'" }) -join ', '

    $query = @"
SELECT
    s.name AS schema_name,
    o.name AS object_name,
    o.type_desc,
    m.definition
FROM sys.sql_modules m
INNER JOIN sys.objects o ON m.object_id = o.object_id
INNER JOIN sys.schemas s ON o.schema_id = s.schema_id
WHERE s.name NOT IN ('sys', 'INFORMATION_SCHEMA')
  AND s.name NOT IN ($excludedSchemaList)
  AND o.is_ms_shipped = 0
ORDER BY s.name, o.type_desc, o.name
"@

    return Get-SqlData -Query $query -Instance $Instance -DatabaseName $DatabaseName -Timeout 120 -MaxCharLength 1000000
}

<# ============================================================================
   FUNCTIONS: REGISTRY EXPORT
   ----------------------------------------------------------------------------
   Generation of the Platform Registry markdown snapshot. Runs each registry
   query in $script:RegistryExports, renders each result set as a markdown
   table, and returns the assembled document plus the count of tables that
   rendered, so the caller can both write the snapshot and report how many
   tables it covered.
   Prefix: (none)
   ============================================================================ #>

# Builds the Platform Registry markdown snapshot and returns a hashtable with the Markdown string and the TableCount of tables rendered.
function Get-RegistryExportMarkdown {
    param(
        [string]$Instance = $script:XFActsServerInstance,
        [string]$DatabaseName = $script:XFActsDatabase
    )

    $lines = @()
    $lines += "# xFACts Platform Registry"
    $lines += "Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
    $lines += ""

    $tableCount = 0

    foreach ($export in $script:RegistryExports) {
        try {
            $rows = Get-SqlData -Query $export.Query -Instance $Instance -DatabaseName $DatabaseName -Timeout 60

            $rowCount = @($rows).Count
            if ($rowCount -eq 0) {
                Write-Log "  SKIP  $($export.Title) - no rows"
                continue
            }

            $lines += "## $($export.Title)"
            $lines += ""

            # Column names from the first row, excluding DataRow system properties.
            $columns = $rows[0].PSObject.Properties |
                Where-Object { $_.Name -notin @('RowError', 'RowState', 'Table', 'ItemArray', 'HasErrors') } |
                ForEach-Object { $_.Name }

            $lines += "| " + ($columns -join " | ") + " |"
            $lines += "| " + (($columns | ForEach-Object { "---" }) -join " | ") + " |"

            foreach ($row in $rows) {
                $values = foreach ($col in $columns) {
                    $val = $row.$col
                    if ($null -eq $val -or $val -is [DBNull]) { "" }
                    else { [string]$val -replace '\|', '\|' -replace '\r?\n', ' ' }
                }
                $lines += "| " + ($values -join " | ") + " |"
            }

            $lines += ""
            $tableCount++
            Write-Log "  OK    $($export.Title) - $rowCount rows" "SUCCESS"
        }
        catch {
            Write-Log "  ERROR  $($export.Title) - $($_.Exception.Message)" "ERROR"
        }
    }

    return @{
        Markdown   = ($lines -join "`n")
        TableCount = $tableCount
    }
}

<# ============================================================================
   FUNCTIONS: GITHUB REST API
   ----------------------------------------------------------------------------
   Thin wrappers over the GitHub REST API shared by the publish run and the
   manifest builder: request header construction, repository tree retrieval,
   single-file create/update and delete via the Contents API, and local git blob
   SHA computation for change detection without downloading remote content.
   Prefix: (none)
   ============================================================================ #>

# Builds the GitHub REST request headers carrying the bearer token and API version.
function Get-GitHubHeaders {
    param([string]$Token)
    return @{
        "Authorization"        = "Bearer $Token"
        "Accept"               = "application/vnd.github+json"
        "User-Agent"           = "xFACts-Publisher/1.0"
        "X-GitHub-Api-Version" = "2022-11-28"
    }
}

# Retrieves the full repository file tree via the Git Trees API as a path -> blob SHA map.
function Get-RepoTree {
    param(
        [string]$Owner,
        [string]$Repo,
        [string]$Branch,
        [hashtable]$Headers
    )

    $uri = "https://api.github.com/repos/$Owner/$Repo/git/trees/${Branch}?recursive=1"

    try {
        $response = Invoke-RestMethod -Uri $uri -Headers $Headers -Method Get -TimeoutSec 30
        $fileMap = @{}

        foreach ($item in $response.tree) {
            if ($item.type -eq "blob") {
                $fileMap[$item.path] = $item.sha
            }
        }

        return $fileMap
    }
    catch {
        Write-Log "Failed to retrieve repo tree: $($_.Exception.Message)" "ERROR"
        return $null
    }
}

# Creates or updates a single repository file via the Contents API (SHA required for updates, null for creates).
function Push-GitHubFile {
    param(
        [string]$Owner,
        [string]$Repo,
        [string]$Branch,
        [hashtable]$Headers,
        [string]$RepoPath,
        [byte[]]$ContentBytes,
        [string]$CommitMessage,
        [string]$ExistingSha = $null
    )

    $uri = "https://api.github.com/repos/$Owner/$Repo/contents/$RepoPath"

    $body = @{
        message = $CommitMessage
        content = [Convert]::ToBase64String($ContentBytes)
        branch  = $Branch
    }

    if ($ExistingSha) {
        $body.sha = $ExistingSha
    }

    $jsonBody = $body | ConvertTo-Json -Compress

    try {
        $response = Invoke-RestMethod -Uri $uri -Headers $Headers -Method Put `
            -Body $jsonBody -ContentType "application/json; charset=utf-8" -TimeoutSec 30
        return $response
    }
    catch {
        $statusCode = $null
        if ($_.Exception.Response) {
            $statusCode = [int]$_.Exception.Response.StatusCode
        }
        Write-Log "  FAILED  $RepoPath (HTTP $statusCode): $($_.Exception.Message)" "ERROR"
        return $null
    }
}

# Deletes a repository file via the Contents API (SHA required).
function Remove-GitHubFile {
    param(
        [string]$Owner,
        [string]$Repo,
        [string]$Branch,
        [hashtable]$Headers,
        [string]$RepoPath,
        [string]$Sha,
        [string]$CommitMessage
    )

    $uri = "https://api.github.com/repos/$Owner/$Repo/contents/$RepoPath"

    $body = @{
        message = $CommitMessage
        sha     = $Sha
        branch  = $Branch
    } | ConvertTo-Json -Compress

    try {
        $response = Invoke-RestMethod -Uri $uri -Headers $Headers -Method Delete `
            -Body $body -ContentType "application/json; charset=utf-8" -TimeoutSec 30
        return $true
    }
    catch {
        Write-Log "  FAILED  DELETE $RepoPath : $($_.Exception.Message)" "ERROR"
        return $false
    }
}

# Computes the git blob SHA1 of file content (SHA1 of "blob <size>\0<content>") for change detection without downloading.
function Get-GitBlobSha {
    param([byte[]]$ContentBytes)

    $header = [System.Text.Encoding]::ASCII.GetBytes("blob $($ContentBytes.Length)`0")
    $fullContent = New-Object byte[] ($header.Length + $ContentBytes.Length)
    [Array]::Copy($header, 0, $fullContent, 0, $header.Length)
    [Array]::Copy($ContentBytes, 0, $fullContent, $header.Length, $ContentBytes.Length)

    $sha1 = [System.Security.Cryptography.SHA1]::Create()
    $hashBytes = $sha1.ComputeHash($fullContent)
    $sha1.Dispose()

    return [BitConverter]::ToString($hashBytes).Replace("-", "").ToLower()
}

<# ============================================================================
   FUNCTIONS: OBJECT REGISTRY LOOKUP
   ----------------------------------------------------------------------------
   The Object_Registry enrichment lookup shared by the publish audit and the
   manifest builder. Get-ObjectRegistryLookup loads the active registry rows into
   a filename-keyed table; Resolve-ObjectRegistryEntry maps one repository path to
   its registry entry (generated SQL objects by schema.object, all other files by
   filename), so module and component enrichment is resolved the same way in every
   caller.
   Prefix: (none)
   ============================================================================ #>

# Loads active dbo.Object_Registry rows into a lookup keyed by object_name (each value a list of matching entries).
function Get-ObjectRegistryLookup {
    param(
        [string]$Instance = $script:XFActsServerInstance,
        [string]$DatabaseName = $script:XFActsDatabase
    )

    $query = @"
SELECT
    r.object_name,
    r.object_path,
    r.object_category,
    r.object_type,
    r.module_name,
    r.component_name
FROM dbo.Object_Registry r
WHERE r.is_active = 1
"@

    $rows = Get-SqlData -Query $query -Instance $Instance -DatabaseName $DatabaseName -Timeout 60

    $lookup = @{}
    if ($rows) {
        foreach ($row in @($rows)) {
            $name = $row.object_name
            if (-not $lookup.ContainsKey($name)) {
                $lookup[$name] = @()
            }
            $lookup[$name] += @{
                object_path     = if ($row.object_path -is [DBNull]) { $null } else { [string]$row.object_path }
                object_category = [string]$row.object_category
                object_type     = [string]$row.object_type
                module_name     = if ($row.module_name -is [DBNull]) { $null } else { [string]$row.module_name }
                component_name  = if ($row.component_name -is [DBNull]) { $null } else { [string]$row.component_name }
            }
        }
    }

    return $lookup
}

# Resolves a repository path to its Object_Registry entry (generated SQL dump by schema.object, all other files by filename); returns $null when unregistered.
function Resolve-ObjectRegistryEntry {
    param(
        [string]$RepoPath,
        [hashtable]$Lookup
    )

    $fileName = $RepoPath.Split('/')[-1]

    # Generated SQL object dump: files are <schema>.<object>.sql. Match the object
    # name within the Database category, falling back to the schema.object key.
    if ($RepoPath -like 'xFACts-Generated/sql/*.sql') {
        $identifier = $fileName.Substring(0, $fileName.Length - 4)
        $parts = $identifier.Split('.')
        if ($parts.Count -eq 2) {
            $objectName = $parts[1]
            if ($Lookup.ContainsKey($objectName)) {
                $entry = $Lookup[$objectName] | Where-Object { $_.object_category -eq 'Database' } | Select-Object -First 1
                if ($entry) { return $entry }
            }
            if ($Lookup.ContainsKey($identifier)) {
                return $Lookup[$identifier][0]
            }
        }
        return $null
    }

    # File-based objects: match by filename.
    if ($Lookup.ContainsKey($fileName)) {
        return $Lookup[$fileName][0]
    }

    return $null
}

<# ============================================================================
   FUNCTIONS: MANIFEST GENERATION
   ----------------------------------------------------------------------------
   The shared manifest builder. Publish-RepositoryManifests reads the live GitHub
   repository tree at build time, routes each managed path to its segment via
   $script:ManifestSegments, tags it authored or generated by prefix, enriches it
   from Object_Registry, builds the per-segment and master manifests (each file
   entry carrying a fresh cache-buster raw_url), and pushes only the manifests
   whose content changed. Building from the live tree makes the manifest correct
   by construction for any caller regardless of staging-clone freshness.
   Prefix: (none)
   ============================================================================ #>

# Rebuilds the segmented manifest set from the live GitHub repository tree and pushes changed manifests; returns a status hashtable.
function Publish-RepositoryManifests {
    param(
        [string]$Owner,
        [string]$Repo,
        [string]$Branch,
        [hashtable]$Headers,
        [bool]$Execute = $false,
        [string]$Instance = $script:XFActsServerInstance,
        [string]$DatabaseName = $script:XFActsDatabase
    )

    Write-Log ""
    Write-Log "Generating segmented manifests"
    Write-Log "------------------------------"

    # Read the repository tree at build time - the manifest describes exactly what
    # is in the repo now, including anything pushed earlier in this same run.
    $repoTree = Get-RepoTree -Owner $Owner -Repo $Repo -Branch $Branch -Headers $Headers
    if ($null -eq $repoTree) {
        Write-Log "  Failed to retrieve repository tree; manifests not built." "ERROR"
        return @{ Built = $false; Pushed = 0; Skipped = 0; Failed = 0 }
    }

    $registryLookup = Get-ObjectRegistryLookup -Instance $Instance -DatabaseName $DatabaseName

    $baseRawUrl = "https://raw.githubusercontent.com/$Owner/$Repo/$Branch"
    $cacheBuster = (Get-Date).ToUniversalTime().ToString("yyyyMMddHHmmss")
    $generatedTimestamp = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")

    # Route each repo path into its segment bucket (first matching prefix wins,
    # most-specific first). Paths matching no segment (root manifests and other
    # root files) are not part of any segment and are excluded from the listing.
    $subManifestBuckets = @{}
    $unroutedCount = 0

    foreach ($repoPath in ($repoTree.Keys | Sort-Object)) {
        $segmentKey = $null
        foreach ($segment in $script:ManifestSegments) {
            if ($repoPath.StartsWith($segment.Prefix)) {
                $segmentKey = $segment.Key
                break
            }
        }

        if ($null -eq $segmentKey) {
            $unroutedCount++
            continue
        }

        $fileClass = if ($repoPath.StartsWith("xFACts-Generated/")) { "generated" } else { "authored" }

        if (-not $subManifestBuckets.ContainsKey($segmentKey)) {
            $subManifestBuckets[$segmentKey] = @()
        }

        $fileEntry = [ordered]@{
            path    = $repoPath
            class   = $fileClass
            raw_url = "$baseRawUrl/${repoPath}?v=$cacheBuster"
        }

        # Enrich with module/component from Object_Registry.
        $regEntry = Resolve-ObjectRegistryEntry -RepoPath $repoPath -Lookup $registryLookup
        if ($regEntry) {
            $fileEntry.module    = $regEntry.module_name
            $fileEntry.component = $regEntry.component_name
        }

        $subManifestBuckets[$segmentKey] += $fileEntry
    }

    if ($unroutedCount -gt 0) {
        Write-Log "  $unroutedCount repository path(s) outside all segment prefixes were not listed (root manifests, etc.)"
    }

    # Generate each sub-manifest and collect its summary for the master index.
    $subManifestSummaries = @()
    # repoPath -> bytes, for pushing.
    $allManifestFiles = @{}

    foreach ($segment in $script:ManifestSegments) {
        $files = if ($subManifestBuckets.ContainsKey($segment.Key)) { $subManifestBuckets[$segment.Key] } else { @() }

        $subManifest = [ordered]@{
            generated  = $generatedTimestamp
            category   = $segment.Title
            segment    = $segment.Key
            file_count = $files.Count
            files      = @($files)
        }

        $subJson = $subManifest | ConvertTo-Json -Depth 4
        $subBytes = [System.Text.Encoding]::UTF8.GetBytes($subJson)
        $allManifestFiles[$segment.Filename] = $subBytes

        $subManifestSummaries += [ordered]@{
            category   = $segment.Title
            segment    = $segment.Key
            filename   = $segment.Filename
            raw_url    = "$baseRawUrl/$($segment.Filename)?v=$cacheBuster"
            file_count = $files.Count
        }

        Write-Log "  Sub-manifest: $($segment.Filename) - $($files.Count) files"
    }

    # Build the routing table (repo path prefix -> owning segment manifest),
    # most-specific first, so a consumer can resolve which segment holds any path
    # from the master manifest alone.
    $routingTable = @()
    foreach ($segment in $script:ManifestSegments) {
        $routingTable += [ordered]@{
            prefix   = $segment.Prefix
            segment  = $segment.Key
            manifest = $segment.Filename
        }
    }

    # Generate the master manifest (index plus routing table).
    $totalFileCount = 0
    foreach ($s in $subManifestSummaries) { $totalFileCount += $s.file_count }

    $masterManifest = [ordered]@{
        generated    = $generatedTimestamp
        repository   = "https://github.com/$Owner/$Repo"
        base_raw_url = $baseRawUrl
        file_count   = $totalFileCount
        routing      = @($routingTable)
        manifests    = @($subManifestSummaries)
    }

    $masterJson = $masterManifest | ConvertTo-Json -Depth 4
    $masterBytes = [System.Text.Encoding]::UTF8.GetBytes($masterJson)
    $allManifestFiles["manifest.json"] = $masterBytes

    Write-Log "  Master manifest: $($subManifestSummaries.Count) sub-manifests, $totalFileCount total files"

    $pushCount = 0
    $skipCount = 0
    $failCount = 0

    if ($Execute) {
        foreach ($manifestPath in $allManifestFiles.Keys) {
            $manifestBytes = $allManifestFiles[$manifestPath]

            # Resolve the existing SHA, if the manifest is already in the remote.
            $existingSha = $null
            if ($repoTree.ContainsKey($manifestPath)) {
                $existingSha = $repoTree[$manifestPath]
            }

            # Push only when content actually changed.
            $localSha = Get-GitBlobSha -ContentBytes $manifestBytes
            $contentChanged = ($null -eq $existingSha) -or ($localSha -ne $existingSha)

            if ($contentChanged) {
                $result = Push-GitHubFile -Owner $Owner -Repo $Repo -Branch $Branch -Headers $Headers `
                    -RepoPath $manifestPath -ContentBytes $manifestBytes `
                    -CommitMessage "Update $manifestPath" `
                    -ExistingSha $existingSha

                if ($result) {
                    Write-Log "  PUSH  $manifestPath" "SUCCESS"
                    $pushCount++
                }
                else {
                    Write-Log "  FAILED  $manifestPath" "ERROR"
                    $failCount++
                }

                Start-Sleep -Milliseconds 100
            }
            else {
                $skipCount++
            }
        }

        Write-Log "  Manifests: $pushCount pushed, $skipCount unchanged, $failCount failed"
    }
    else {
        Write-Log "  PREVIEW - Manifests would be pushed:" "WARN"
        foreach ($manifestPath in $allManifestFiles.Keys) {
            Write-Log "    $manifestPath"
        }
    }

    return @{
        Built   = $true
        Pushed  = $pushCount
        Skipped = $skipCount
        Failed  = $failCount
    }
}
